version: '3'

services:
  jobs-app:
    build: ./jobs/.
    ports:
      - 3010:3010
    environment:
      - MONGO_URI=mongodb://db:27017/monoapp
      - APPLICATION_ENDPOINT=http://localhost:3011
  applications-app:
    build: ./applications/.
    ports:
      - 3011:3010
    environment:
      - MONGO_URI=mongodb://db:27017/monoapp
  db:
    image: mongo