version: '3'

services:
  jobs-app:
    build: ./jobs/.
    ports:
      - 3010:3010
    environment:
      - MONGO_URI=mongodb://jobs-db:27017/wttw
      - APPLICATION_ENDPOINT=http://localhost:3011
  applications-app:
    build: ./applications/.
    ports:
      - 3011:3010
    environment:
      - MONGO_URI=mongodb://applications-db:27017/wttw
  jobs-db:
    image: mongo
  applications-db:
    image: mongo